### ISSUE TITLE
Info DB account suspended, script fails

### ISSUE THREAD

**Issue by ssube** [cdown/tzupdate#1]
Any requests to the ipinfodb service used return a message like:

> "ERROR;Your account has been suspended.;x.y.z.w;;;;;;0;0;"

It appears that the account whose keys are baked into the script has been suspended.

Taking the account keys as command-line params rather than distributing them in the script should solve that issue pretty well.

**Comment by cdown** [comment]
Eh, there should at least be a default set of API keys for people to use. You shouldn't have to configure API keys for something this simple (but it's true, they should be able to be taken from the command line). This is one reason why requiring API keys for requests like this is just plain stupid.

Ideally I'd like to find services that actually have sensible APIs.

**Comment by ssube** [comment]
The current default keys are banned, making it tricky to use the script without editing it. Would you be open to a PR for taking keys from the command line?

**Comment by cdown** [comment]
Yeah, sure. My previous reply doesn't preclude that :-) I'm on vacation, otherwise I'd do it myself, but it should be fairly trivial. I would suggest in that case removing

**Comment by cdown** [comment]
Well, I didn't mean to do that.

**Comment by cdown** [comment]
@ssube Let me know what you think about the above changes. I'll merge them in soon.

**Comment by cdown** [comment]
0.4.0 is going out soon with this fixed. I'll upload once PyPi stops giving 503 errors.

**Comment by cdown** [comment]
0.4.0 released.
