### ISSUE TITLE
Error when /etc/localtime doesn't exist

### ISSUE THREAD

**Issue by justin8** [cdown/tzupdate#11]
If I run tzupdate on a new machine that doesn't have a timezone set yet, it has a no such file or directory '/etc/localtime' error. Touching the file first makes it work as expected.

**Comment by cdown** [comment]
Thanks for reporting! I'm surprised that there are still new machines that have no /etc/localtime at all, but I guess it's not *all* that surprising.

I believe I've just fixed this with 7146a11e128f which is being tested on Travis now, let me know if you have any other issues. I'll merge into develop once the tests successfully ran. :-)

**Comment by justin8** [comment]
I was using it in a build script for Arch :) Thanks for the quick response
