### ISSUE TITLE
Installation package for distributions

### ISSUE THREAD

**Issue by jmgomezpoveda** [cdown/tzupdate#13]
This is a great piece of software, little known.

For easier installation and distribution, it would be great to have this packaged in deb format for Ubuntu/Debian/Mint, and maybe as rpm/\* for other distributions as well.

**Comment by cdown** [comment]
It's already packaged for [Arch Linux](https://aur.archlinux.org/packages/tzupdate/), but yes, there's no packaging right now for deb/rpm.

Seems reasonable to maybe use pex+fpm for this.

**Comment by cdown** [comment]
I'll leave this up to the distribution or PPA maintainers to do. Feel free to reopen if you are interested in maintaining such a package.
