### ISSUE TITLE
Automatically set timezone when nework becomes available

### ISSUE THREAD

**Issue by gi1242** [cdown/tzupdate#133]
Thanks for this script. I just set it up so it automatically sets the timezone when the network becomes available. If you find it useful and want to distribute some version of it with your script, here's what I did:

Create `/etc/NetworkManager/dispatcher.d/update-timezone.sh` with
```
#! /bin/bash
# Automatically set time zone when connected to the network

iface=$1
action=$2

#logger "tzupdate $iface $action"

if [[ $iface == wlan0 && $action == up ]]; then
    tz=$(tzupdate -s 1 -p 2>/dev/null)
    if [[ -n $tz && -r /usr/share/zoneinfo/$tz ]]; then
	timedatectl set-timezone $tz
    fi
fi
```
(Change `$iface == wlan0` to `$iface != lo` if desired, and don't forget to make the script executable.)

This only works for systems that use NetworkManager.

GI

**Comment by 99linesofcode** [comment]
Is there a reason why a systemd service that runs on `network.online.target` isn't provided by default?

**Comment by cdown** [comment]
Thanks for the script!

> Is there a reason why a systemd service that runs on network.online.target isn't provided by default?

#31 covers pretty well (with an immediate example...) why that's not recommended. I'm going to close this for now, unless there is some new information that wasn't available previously.
