### ISSUE TITLE
Permission denied (os error 13)

### ISSUE THREAD

**Issue by sazawal** [cdown/tzupdate#134]
After smoothly installing tzupdate with cargo. The `tzupdate --help` is working fine. But on running `tzupdate`, the following error shows up,

```
Error: Permission denied (os error 13) at path "/etc/.tmpTEScGV"
```

Looks like the executable at ~/.cargo/bin does not have the permissions to write to the timezone file in the /etc directory

**Comment by cdown** [comment]
You need to run as root, otherwise how are you going to change /etc :-)

**Comment by sazawal** [comment]
Thanks for the answer, but it doesn't work as root even. It looks like it doesn't find the .cargo installation directory when run as root

```
[user@archlinux]$ sudo tzupdate
[sudo] password for user: 
sudo: tzupdate: command not found
```

**Comment by cdown** [comment]
You are not passing your $PATH through `sudo`, you have `secure_env` or similar set. Either pass $PATH, or use the full path. Either way, not a tzupdate issue.
