### ISSUE TITLE
Print detected timezone only

### ISSUE THREAD

**Issue by ThomDietrich** [cdown/tzupdate#18]
Hey, great project! The option `--print-only` will currently output "Set system timezone to WHATEVER.". For further processing in other software it would be handy to only return the timezone string. This could be either changed for `print-only` or done for an additional argument. Whatever you prefer ;) Thanks!

**Comment by cdown** [comment]
Yeah, agreed. This is an artefact from the old days when we just reused the same code (and omitted the linking step). Now it should only print the timezone and nothing else.

**Comment by cdown** [comment]
Merged as f880e59.

**Comment by cdown** [comment]
Released as 1.2.0 to PyPi and AUR.

**Comment by ThomDietrich** [comment]
👍  thanks man!
