### ISSUE TITLE
Integrate Google Maps geolocation api

### ISSUE THREAD

**Issue by PolarPayne** [cdown/tzupdate#19]
The current implementation works fine on a lot of cases, but VPNs and mobile networks will often give you a wrong location.
Using the Google Maps geolocation API on devices with a WIFI card would improve the accuracy **a lot**. The main problem with this is ofcourse that this API requires an API key, but this could be read from a file.

https://developers.google.com/maps/documentation/geolocation/intro

This is also something I could personally work on, and submit a pull request.

**Comment by cdown** [comment]
Realistically I'm unlikely to implement this soon, but feel free to send a PR :-)

**Comment by cdown** [comment]
Closing based on staleness without prejudice. Feel free to reopen if you intend to work on this.
