### ISSUE TITLE
Installing with pip and running with sudo doesn't work

### ISSUE THREAD

**Issue by hwsamuel** [cdown/tzupdate#20]
Background: I'm using Ubuntu 16.04. I installed pip itself without root (because I think that's not really needed, right?)

Issue: When I install tzupate via pip, it installs fine. But when I run with sudo, I get the error "tzupdate: command not found"

**Comment by cdown** [comment]
This is a problem with your environment, not with tzupdate. You need to make sure that `$PATH` is propagated correctly through sudo: https://stackoverflow.com/a/18560604/945780
