### ISSUE TITLE
sudo vs real root

### ISSUE THREAD

**Issue by eriktux** [cdown/tzupdate#21]
Hi,
this is not really an "issue", but rather, a question...

If I run:
`tzupdate -a 64.37.57.114`

Answer is:
`Set system timezone to America/New_York.`

Cool thing is, tzupdate also changed the time on my system!
```
date
Sun Jan 14 22:41:19 EST 2018
```

But, if I run tzupdate as regular, non-root user, using sudo:
`sudo tzupdate -a 64.37.57.114`

Answer is:
`Set system timezone to America/New_York.`

Which is what I want, but running the date command shows:
```
date
Mon Jan 15 03:42:48 UTC 2018
```

Why is it?  Why is it NOT updating the time, when run through sudo?

**Comment by cdown** [comment]
Huh, that's intriguing. If tzupdate exited without error, it should have done the same thing.

What does `stat /etc/localtime` say? Which distribution is this?

**Comment by eriktux** [comment]
It's Ubuntu 16.04.

`stat /etc/localtime 
  File: '/etc/localtime' -> '/usr/share/zoneinfo/America/New_York'
  Size: 36              Blocks: 0          IO Block: 4096   symbolic link
Device: 5fh/95d Inode: 1300        Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-01-15 21:30:35.980517343 +0000
Modify: 2018-01-15 21:30:35.980517343 +0000
Change: 2018-01-15 21:30:35.980517343 +0000
 Birth: -
`

**Comment by cdown** [comment]
Does this same behaviour occur with `dpkg-reconfigure tzdata` with "real" root and sudo?

**Comment by eriktux** [comment]
dpkg-reconfigure tzdata seems to be **interactive**, it's ok like that?
So I choose America/New-York for my first test.  Here are the **results**...

If I run as "real" root:
```
...
Current default time zone: 'America/New_York'
Local time is now:      Mon Jan 15 19:11:05 EST 2018.
Universal Time is now:  Tue Jan 16 00:11:05 UTC 2018.

date
Mon Jan 15 19:11:12 EST 2018
```

If I run as "sudo" (let's try Antartica):
```
...
Current default time zone: 'Antarctica/Davis'
Local time is now:      Tue Jan 16 07:15:35 +07 2018.
Universal Time is now:  Tue Jan 16 00:15:35 UTC 2018.

date
Tue Jan 16 00:16:18 UTC 2018
```

So this answer your question: Yes it seems like I'm having the same problem when I run your command.  Why is it?

I also noticed something strange:
If I run the "date" command as root, I see actual date/time.
If I run the "date" command as sudo, I see UTC time!

So the user and root don't even have the same time... Isn't it weird?
For user, it seems like no matter what I try, it keeps showing UTC time.

**Comment by cdown** [comment]
What's the output of `env` and `type date`?

**Comment by eriktux** [comment]
as user:

```
env
SCREEN_HEIGHT=1020
HOSTNAME=zeck
DEBCONF_NONINTERACTIVE_SEEN=true
TERM=screen-256color
SCREEN_WIDTH=1360
LC_ALL=en_US.UTF-8
LS_COLORS=(removed for readability)
COLUMNS=268
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/home
NODE_UNREGISTER_IF_STILL_DOWN_AFTER=60000
SCREEN_DEPTH=24
LANG=en_US.UTF-8
**TZ=UTC**
LINES=74
HOME=/home/erik
LANGUAGE=en_US:en
DBUS_SESSION_BUS_ADDRESS=/dev/null
DEBIAN_FRONTEND=noninteractive
DISPLAY=:99.0
_=/usr/bin/env

type date
date is /bin/date
```


As root:

```
env
SHELL=/bin/bash
TERM=screen-256color
USER=root
LS_COLORS=(removed for readability)
MAIL=/var/mail/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/root
HOME=/root
LOGNAME=root
DISPLAY=:99.0
_=/usr/bin/env


date
date is /bin/date
```

**Comment by cdown** [comment]
Yeah, having `TZ` set to `UTC` will do that.

It's probably set somewhere in your bash profile/rc, or the global one. There are some tips on finding out where it may have came from here: https://unix.stackexchange.com/q/813/10762

For now, you can also do `unset TZ; date`.

**Comment by eriktux** [comment]
It works!  Thank you so much.
I've been banging my head on the wall for a while, because of this  ;)
