### ISSUE TITLE
freegeoip.net deprecated

### ISSUE THREAD

**Issue by kewlfft** [cdown/tzupdate#23]
Hello
freegeoip.net is going to be deprecated in July
Thanks

**Comment by freegeoipapp** [comment]
I've setup
https://freegeoip.app

- HTTPS (no HTTP, sorry - it's 2018)
- Rate limit of 15000/hour as before for FREE, guaranteed
- No logs, no analytics - privacy alway in mind

It's the same api - just a different TLD ;) let me know if you have any problems integrating.
