### ISSUE TITLE
freegeoip seems to have switched to an account model

### ISSUE THREAD

**Issue by bjmnbraun** [cdown/tzupdate#24]
As of July 2018, acc to https://github.com/apilayer/freegeoip#readme, freegeoip has started returning "deprecated" responses when used. They now require API keys to use their service.

Commenting out the freegeoip option is a workaround to prevent an exception when the deprecated response is received, the other options seem to work just fine.

**Comment by cdown** [comment]
Are you sure you're using the latest version? This should already have been dealt with in 91c9609671f944cd5a9eb5e1fb312f21f6119dea.

**Comment by cdown** [comment]
I don't see any problems here per the previous comment.
