### ISSUE TITLE
ENH: API for get_timezone_for_ip

### ISSUE THREAD

**Issue by jbrockmendel** [cdown/tzupdate#26]
I have some not-that-old code that called `tzname = tzupdate.get_timezone_for_ip()` that is breaking after updating to the latest version.  It looks like the same behavior is still available via the CLI via `tzupdate -p`, but I don't see a nice way to get the same behavior via python.  Would a PR to restore that functionality (presumably under a new name) be accepted?

**Comment by cdown** [comment]
Hmm, tzupdate isn't really designed for use as a library :-)

That said, as long as it doesn't cause too much churning or extra complexity in the code, I'm ok with it. Probably the best thing to do is do something with this function signature:

    def get_timezone_for_ip(ip=None, service=None, queue_obj=None):

Then you can have some logic changes if these are None or not.

**Comment by jbrockmendel** [comment]
Great, I’ll make a PR, thanks.

FWIW my use case is checking that the detected time zone matches the system tz and warning if it doesn’t.  This runs without root privileges, so can’t update the system directly.

**Comment by cdown** [comment]
In that case, maybe you can just open a subprocess with `tzupdate -p`?

Either way, a PR sounds fine as long as it doesn't require too drastic restructuring :-)
