### ISSUE TITLE
Consider checking which timezone path the system uses

### ISSUE THREAD

**Issue by pigmonkey** [cdown/tzupdate#29]
I use Arch, which sets the timezone via the `/etc/localtime` symbolic link.

Recently I had a calendar program which was displaying events in the wrong timezone, despite things like `date` and `timedatectl` showing the correct timezone. I couldn't figure out where it was getting the incorrect configuration from.

As it turns out, I had run `tzupdate` when I was in a different timezone, which both set the `/etc/localtime` link and wrote the timezone to `/etc/timezone`. Later, when I returned to my home timezone, I changed the timezone back using a different method, such that `/etc/localtime` was correct but the `/etc/timezone` file that `tzupdate` created still showed the wrong timezone. This was where the calendar program was getting the incorrect date from.

It would be nice if `tzupdate` only modified the file used by the system. The easiest solution would be to not touch either file unless they already exist, but I see in #11 that `tzupdate` intentionally accounts for the odd case of a system which has no timezone configured yet.

Instead, maybe the best option is to check `/etc/issue`, if the contents look Debian-ish set `/etc/timezone`, otherwise set `/etc/localtime`.

**Comment by cdown** [comment]
I'd rather not get into the business of deciding which file needs to go on which operating system, with a gajillion Debian derivatives to then check. I'd suggest the calendar program in question is probably wrong to use `/etc/timezone` over `/etc/localtime`, which is standard.

I'm afraid I wouldn't merge something checking `/etc/issue`.

**Comment by pigmonkey** [comment]
I agree this was partially a bug in the calendar's attempt to figure out the timezone, but I still think `tzupdate` creating a config file that is inappropriate for the system is unintuitive.

What if the default behaviour of `tzupdate` was to overwrite `/etc/localtime` or `/etc/timezone` only if they existed, but to create both if neither file is found. That way it would do the right thing most of the time, and only create both files in the case of no timezone currently being configured so as to not regress #11.

**Comment by cdown** [comment]
I've been thinking about that, but I'm mostly tentative out of unfamiliarity with (and somewhat lack of support for) Debian's `/etc/timezone` malarkey.

As far as I can tell, on systems with `/etc/timezone`, `/etc/localtime` is still always needed, so I suppose if we do that we should only apply the existence check to `/etc/timezone`.

Why Debian needs yet another file just describing `/etc/timezone`, who knows. Maybe they're literally copying the zoneinfo file, which would be odd.

**Comment by pigmonkey** [comment]
Yeah, I poked around on an Ubuntu box I have and it looks like it does need both, so I think always setting `/etc/localtime` and saving the conditional just for `/etc/timezone` makes sense.

**Comment by cdown** [comment]
Thanks for taking a look.

06646ee094536a984645626274607334db4043a6 should implement this for future cases, although for boxes with `/etc/timezone` already on, it will need to be manually removed.

Thanks for the report!
