### ISSUE TITLE
Add a service file to change the timezone on boot

### ISSUE THREAD

**Issue by Baitinq** [cdown/tzupdate#31]
This service file  (`timezone.service`) could be included in the aur package so that the timezone is changed automatically (if the physical location of the machine is changed). This is not essential but could be useful. Thank you

`[Unit]
Description=Sets timezone automatically (needs internet connection)
Wants=network-online.target
After=network.target network-online.target

[Service]
ExecStart=/usr/bin/tzupdate

[Install]
WantedBy=multi-user.target
`

**Comment by cdown** [comment]
We discussed this a bit in #14, although I'm still not convinced this is likely to work super well.

Clearly it's something people want, though, so feel free to open a PR. :-)

**Comment by ranadl** [comment]
I am trying this out, my machine is on a vehicle moving around, but it keeps updating to chicago time even though its in CA.

this is what i get if i dont do it through root:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tzupdate.py", line 178, in link_localtime
    os.symlink(zoneinfo_tz_path, localtime_temp_path)
PermissionError: [Errno 13] Permission denied: '/usr/share/zoneinfo/America/Chicago' -> '/etc/localtime~'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/tzupdate", line 11, in <module>
    load_entry_point('tzupdate==2.1.0', 'console_scripts', 'tzupdate')()
  File "/usr/local/lib/python3.6/dist-packages/tzupdate.py", line 298, in main
    link_localtime(timezone, args.zoneinfo_path, args.localtime_path)
  File "/usr/local/lib/python3.6/dist-packages/tzupdate.py", line 185, in link_localtime
    ) from thrown_exc
PermissionError: [Errno 13] Could not link "/etc/localtime~" ([Errno 13] Permission denied: '/usr/share/zoneinfo/America/Chicago' -> '/etc/localtime~'). Are you root?

**Comment by cdown** [comment]
Well, there's really nothing we can do about that. If your geolocation is wrong, then you're SOL. For most mobile packages, that IP range has totally generic information.

**Comment by cdown** [comment]
I'm not convinced this is useful, and nobody has submitted a PR in two years, so closing.
