### ISSUE TITLE
Error in tzupdate

### ISSUE THREAD

**Issue by Baitinq** [cdown/tzupdate#32]
Hello and thanks for your program,

I am getting the following error when running the script:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/tzupdate.py", line 64, in get_timezone
    timezone = q.get(block=True, timeout=timeout)
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tzupdate", line 11, in <module>
    load_entry_point('tzupdate==1.5.0', 'console_scripts', 'tzupdate')()
  File "/usr/lib/python3.7/site-packages/tzupdate.py", line 279, in main
    timezone = get_timezone(args.ip, timeout=args.timeout, services=services)
  File "/usr/lib/python3.7/site-packages/tzupdate.py", line 67, in get_timezone
    "No usable response from any API in {} seconds".format(timeout)
tzupdate.TimezoneAcquisitionError: No usable response from any API in 5.0 seconds

I have checked if I have an internet connection and I do.
Is this just me or has the api deprecated?

Thanks a lot.

**Comment by cdown** [comment]
Hi there,

> Is this just me or has the api deprecated?

If you get this, it means that *all* APIs didn't respond within 5 seconds. Even if one is not working, that won't cause this.

What does running with `--debug` show, and which version are you running?

**Comment by Baitinq** [comment]
When i run it with debug i get:
`DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ipapi.co:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): freegeoip.app:443
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): ip-api.com:80
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): worldtimeapi.org:80
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/tzupdate.py", line 64, in get_timezone
    timezone = q.get(block=True, timeout=timeout)
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tzupdate", line 11, in <module>
    load_entry_point('tzupdate==1.5.0', 'console_scripts', 'tzupdate')()
  File "/usr/lib/python3.7/site-packages/tzupdate.py", line 279, in main
    timezone = get_timezone(args.ip, timeout=args.timeout, services=services)
  File "/usr/lib/python3.7/site-packages/tzupdate.py", line 67, in get_timezone
    "No usable response from any API in {} seconds".format(timeout)
tzupdate.TimezoneAcquisitionError: No usable response from any API in 5.0 seconds`

I am using the version 1.5.0-1 (latest in arch repos)

**Comment by cdown** [comment]
Okay, so none of those sites had any errors (or you would see it in the debug output), they just didn't respond within 5 seconds.

This seems like something localised to your internet setup. Judging by the fact that you never even send the GET request, there might be something wrong with your DNS.

**Comment by Baitinq** [comment]
I'm not at home atm, I'll send u the output of that curl later although I believe I use ip-api for another program (to get my weather based on my location and it works fine). I am using cloudfares dns (1.1.1.1). Can this be a problem? Maybe the problem is even with my /etc/hosts. I'll try removing it and seeing what happens as soon as I get home. Thx for the help

**Comment by Baitinq** [comment]
I just got home and the time to run that command is 5.42s. That is probably why it doesnt work. Maybe you could make it so that instead of waiting only for 5s it waited for 6s? Thx

**Comment by cdown** [comment]
For now, you can use `tzupdate --timeout 6` :-)

That said, I'll bump the timeout. That latency is massive though, much more than I expected any successful request could be :-)

**Comment by Baitinq** [comment]
Thanks a lot
