### ISSUE TITLE
version 2.0.0 compatibility issues python2/3 symlink

### ISSUE THREAD

**Issue by pshlos46** [cdown/tzupdate#34]
After updating to 2.0.0, an invalid syntax error poped

```tgeo-work:  ~ 
→ sudo tzupdate
Traceback (most recent call last):
  File "/home/tgeo/.local/bin/tzupdate", line 5, in <module>
    from tzupdate import main
  File "/home/tgeo/.local/lib/python2.7/site-packages/tzupdate.py", line 69
    ) from None
         ^
SyntaxError: invalid syntax
```
So after troubleshooting this looks like a python version error.
Specifically the script calls in the environment `/usr/bin/python`

```tgeo-work:  ~ 
→ cat /home/tgeo/.local/bin/tzupdate
#!/usr/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from tzupdate import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
So the script makes the assumption that `/usr/bin/python` points to `python3` but in Ubuntu 18.04.3 LTS and as a general good practice (according to [PEP394](https://legacy.python.org/dev/peps/pep-0394/)) `python` symlink **should point** to `python2` actually and not `python3`.

```tgeo-work:  ~ 
→ cat /etc/os-release | grep VERSION
VERSION="18.04.3 LTS (Bionic Beaver)"
VERSION_ID="18.04"
VERSION_CODENAME=bionic
tgeo-work:  ~ 
→ which python && which python2 && which python3
/usr/bin/python
/usr/bin/python2
/usr/bin/python3
tgeo-work:  ~ 
→ /usr/bin/python --version && /usr/bin/python2 --version && /usr/bin/python3 --version
Python 2.7.17
Python 2.7.17
Python 3.6.9
```
Shouldn't we follow the recommendation in the above mentioned PEP?

> python2 will refer to some version of Python 2.x.
> python3 will refer to some version of Python 3.x.
> for the time being, all distributions should ensure that python refers to the same target as python2.

For a workaround, the moment I switched the shebang to `/usr/bin/python3` in `~/.local/bin/tzupdate` everything works, maybe it's worth it pushing this to the main branch too? 

Thanks

**Comment by cdown** [comment]
Python 2 is EOL as of January 1st. You need to upgrade. :-)

**Comment by pshlos46** [comment]
Surely it is EOL, but standards for compatibility reasons still exist. :) Right now when in a major Debian release you type `python` it understands `python2`.

I was thinking of either using `#!/usr/bin/env python3` in the `setup.py` & `tzupdate.py` so it would install always in the correct way no matter where `python` points
**or**
(might be preferable) change in the `README.md` the install command to 
```
$ pip3 install -U tzupdate
```
both would work, (tested using pip3 it installs with python3 and works flawlessly).

I know it is a minor issue and it is really not worth making a fuss about it, but until someday `python` points to `python3` in all major releases I think one of the above workarounds would save some troubleshooting time from people trying this out.

**Comment by cdown** [comment]
It should be more obvious what the issue is, yes. Hopefully 1b75d0d should help there:

```
% tox -e py27
[...]
ERROR: Package 'srt' requires a different Python: 2.7.16 not in '>=3.5'
```

**Comment by cdown** [comment]
It should be more clear, yes. Hopefully 19cd759 should help there:

```
% tox -e py27
ERROR: Package 'tzupdate' requires a different Python: 2.7.16 not in '>=3.5'
```

**Comment by pshlos46** [comment]
that should work too, thanks :)
