### ISSUE TITLE
Add to documentation

### ISSUE THREAD

**Issue by virtuosonic** [cdown/tzupdate#36]
It installed on raspbian by running 
`sudo pip install -U tzupdate`

But it couldn't run, it reported a SyntaxError, it was fixed by uninstalling and installing with pip3

`sudo pip uninstall  tzupdate`
`sudo pip3 install -U tzupdate`

**Comment by cdown** [comment]
tzupdate is Python 3 only :-)

Since Python 2 is EOL, I think it's fine to assume `pip` is Python 3.
