### ISSUE TITLE
Add this terrific documentation

### ISSUE THREAD

**Issue by addyess** [cdown/tzupdate#41]
[This answer](https://unix.stackexchange.com/questions/90325/automatically-set-linux-timezone-according-to-location#answer-424924) on stackexchange was really close to the right solution in 2022.

It just needs some updating for python3 (i mean, installing like this `sudo pip3 install -U tzupdate`) and it would be good as gold

**Comment by cdown** [comment]
tzupdate is now in Rust, nothing to do here.
