### ISSUE TITLE
`http://ip-api.com/json/{ip}` gives inaccurate responses

### ISSUE THREAD

**Issue by addyess** [cdown/tzupdate#42]
successive runs of `tzupdate` was yielding different timezones. 

I noticed that depending on which SERVICE endpoint returned first -- the timezone followed that query response

Perhaps instead of using the first response, you should gather as many non-timeout responses as possible, and have the app vote on which one is correct.  In the event of a tie, don't update the timezone.

**Comment by cdown** [comment]
The IP info db is unreliable anyway, there's no guarantee of accuracy. Therefore I don't see any need to guarantee idempotence either -- this is intended to be run by hand.
