### ISSUE TITLE
"No module named 'tzupdate'"

### ISSUE THREAD

**Issue by Slater91** [cdown/tzupdate#43]
Hello,
First of all thanks for making this! I have been using tzupdate for a while and it has worked fantastically well. Unfortunately it seems to break on Ubuntu 22.04-based distros (currently using KDE neon). If I try to launch tzupdate (`sudo tzupdate`), this is what happens:
```
Traceback (most recent call last):
  File "/usr/local/bin/tzupdate", line 5, in <module>
    from tzupdate import main
ModuleNotFoundError: No module named 'tzupdate'
```
Any idea what might be going on?
I have Python 3.10.6 installed and I installed tzupdate using `pip install -U tzupdate`.

Thank you!

**Comment by cdown** [comment]
Hi! It's probably that your Python site packages dir changed due to version upgrade. setuptools entry point-based tools work by installing a shim and then importing like this.

Does this fix it?

```
pip install -U --force-reinstall tzupdate
```

**Comment by Slater91** [comment]
Unfortunately it doesn't fix it. I did update from Ubuntu 20.04 to 22.04, so this might indeed be part of the issue, but I have no clue whatsoever as for how to fix it.

**Comment by cdown** [comment]
tzupdate is now in Rust, nothing to do here.

**Comment by Slater91** [comment]
The new version works like a charm, thank you!
