### ISSUE TITLE
Proposal: Add Timezone Information from Free IP2Location.io API

### ISSUE THREAD

**Issue by ip2location** [cdown/tzupdate#81]
I wonder if you have plan to support additional IP geolocation API source.

IP2Location.io provides timezone information under its free plan.

If you are interested, we can offer PR with the integration.

**Comment by cdown** [comment]
Hii! A PR to add it would be fine. Requirements:

- HTTPS;
- Access without embedded token (since then anyone can take the token from the source).

**Comment by cdown** [comment]
No PR in one month, closing.
