### ISSUE TITLE
Previous timezone not cleared

### ISSUE THREAD

**Issue by iancboswell** [cdown/tzupdate#93]
When `/etc/timezone` is updated, it seems to not be clearing any existing timezone that was written there before. Specifically, I ran into an issue where a device that had been in `America/Los_Angeles` came to `America/New_York`. That device's `/etc/timezone` then looked like this:

```
America/New_York
es
```

**Comment by cdown** [comment]
Wow! Ok, so yeah, that's a bug. It turns out that glibc seems to handle this ok, so I never noticed it, but that's certainly not intended. Thanks for the report.

**Comment by cdown** [comment]
(er, or rather, glibc doesn't care about this at all, just java and some stuff on debian distros.)

**Comment by iancboswell** [comment]
Excellent, thanks for the fix!
